# Generated by Django 4.0 on 2022-01-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_activation_code'),
        ('main', '0004_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('post', 'user')},
        ),
    ]
